title: Benny Istanto
logo: /assets/img/logo.png
description: Exploring climate with GIS, solving old problems in new ways. Turning satellite data into actionable, life-saving insights.
show_downloads: false
google_analytics: UA-16825012-9
theme: jekyll-theme-minimal
